backend:
  name: git-gateway
  branch: master

media_folder: data/content/_img
public_folder: static
logo_url: https://imperialsplendour.com/static/48e018bbf305f6ff3be8092e37bd2c9d/31987/hero_logo.png

collections:
  - label: "Pages"
    name: "pages"
    files:
    - name: "index"
      label: "Home Page"
      file: "data/content/pages/index.md"
      fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Hero Image", name: "heroImage", widget: "image" }
      - { label: "Hero Logo", name: "heroLogo", widget: "image" }
      - { label: "Hero Logo Alt Text", name: "heroLogoAlt", widget: "string" }
      - { label: "Hero Text", name: "heroText", widget: "markdown" }
      - label: "Info Boxes"
        name: "infoBoxes"
        widget: "list"
        summary: '{{fields.image}} - {{fields.text}}'
        fields:
          - { label: "Info Text", name: "text", widget: "markdown" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Image Alt Text", name: "imgAlt", widget: "string" }
    - name: "about"
      label: "About"
      file: "data/content/pages/about.md"
      fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Contributors Title", name: "contributorsTitle", widget: "string" }
      - label: "Contributors"
        name: "contributors"
        widget: "list"
        summary: '{{fields.avatar}} - {{fields.name}}'
        fields:
          - { label: "Avatar", name: "avatar", widget: "image" }
          - { label: "Name", name: "name", widget: "string" }
    - name: "terms-of-service"
      label: "Terms of Service"
      file: "data/content/pages/terms-of-service.md"
      fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
    - name: "404"
      label: "404"
      file: "data/content/pages/404.md"
      fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Message Title", name: "messageTitle", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Image Alt Text", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "downloads"
    label: "Downloads"
    files:
    - name: "download"
      label: "Download"
      file: "data/content/pages/download.md"
      fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Version", name: "version", widget: "string" }
      - { label: "DownloadTitle", name: "downloadTitle", widget: "string" }
      - label: "Download Links"
        name: "downloadLinks"
        widget: "list"
        summary: '{{fields.host}} - {{fields.link}}'
        fields:
          - { label: "Host", name: "host", widget: "select", options: ["Google Drive", "MediaFire", "ModDB"]}
          - { label: "Link", name: "link", widget: "string" }
      - { label: "Instruction Text", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Blog"
    folder: "data/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    editor:
     preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "factions"
    label: "Factions"
    folder: "data/content/factions"
    create: true
    slug: "{{slug}}"
    extension: "md"
    editor:
     preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Flag", name: "flag", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
